name: Bing Daily Check-in

on:
  schedule:
    # 每天凌晨2点执行（UTC时间，对应北京时间10点）
    - cron: '0 2 * * *'
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  bing-checkin:
    runs-on: ubuntu-latest
    timeout-minutes: 300  # 设置5小时超时
    env:
      PYTHONUNBUFFERED: 1  # 确保Python输出不被缓存
      DISPLAY: :99  # 为无头模式设置显示
      CHROME_BIN: /usr/bin/google-chrome  # Chrome路径
      CHROMEDRIVER_PATH: /usr/local/bin/chromedriver  # ChromeDriver路径
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Chrome and ChromeDriver
      run: |
        # 安装Chrome
        curl -fsSL https://dl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # 安装ChromeDriver
        CHROME_VERSION=$(google-chrome --version | grep -oE "[0-9]+\.[0-9]+\.[0-9]+")
        echo "Chrome version: $CHROME_VERSION"
        
        # 下载对应版本的ChromeDriver
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION"
        CHROMEDRIVER_VERSION=$(cat /tmp/chromedriver.zip)
        wget -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
        
        # 解压并安装
        unzip /tmp/chromedriver.zip -d /usr/local/bin/
        chmod +x /usr/local/bin/chromedriver
        rm /tmp/chromedriver.zip
        
    - name: Verify Chrome and ChromeDriver
      run: |
        google-chrome --version
        which google-chrome
        chromedriver --version
        which chromedriver
        echo "Chrome binary: $CHROME_BIN"
        echo "ChromeDriver path: $CHROMEDRIVER_PATH"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config directory
      run: mkdir -p config
      
    - name: Setup accounts configuration
      run: |
        # 从GitHub Secrets读取账号配置
        echo '${{ secrets.ACCOUNTS_CONFIG }}' > config/accounts.json
        
    - name: Run Bing automation
      run: |
        python bingZDH.py --once
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bing-logs
        path: |
          *.log
          *.png
        retention-days: 7
