
        
    - name: Upload logs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: bing-logs
        path: |
          src/*.log
          src/*.png
        retention-days: 7
